name = "Packwiz"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e6b421fb2cc3eab2660585e028031577d8d2ff1ef6670dbd4875995793caa634"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
