name = "Packwiz"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8aeb10b3d7f1e01af3474ffee230a6fb4499ecfc138599649c6a9e2785ac0e2a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
